{
 "title": "Profit Graph",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "exchanges",
    "query": "show tag values from \"balance\" with key=\"exchange\""
   },
   {
    "name": "inverse_exchange",
    "query": "show tag values from \"balance\" with key=\"exchange\""
   }
  ]
 },
 "panels": [
  {
   "title": "Asset Change Total ($exchanges)",
   "type": "graph",
   "description": "資産額の変動\n（海外取引所などの証拠金の現物の価格変動も含まれます）",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "BTC (Pos)" }
   ],
   "targets": [
    {
     "alias": "Total Asset Change",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(mean) FROM(\n  SELECT mean(cumulative_sum) FROM(\n    SELECT cumulative_sum(\"diff_jpy\") FROM \"balance\" WHERE \"exchange\"=~/$exchanges$/ and $timeFilter GROUP BY \"exchange\"\n  ) GROUP BY \"exchange\", time($__interval)\n) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total Position (include spot)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(pos)+sum(spot) FROM (\n    SELECT pos,spot from (\n        SELECT mean(\"pos\") as pos, mean(\"spot\") as spot FROM \"balance\" WHERE \"exchange\"=~/$exchanges$/ and $timeFilter GROUP BY time($__interval)\n    ) GROUP BY \"exchange\"\n) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Asset change ($exchanges)",
   "type": "graph",
   "description": "資産額の変動\n（海外取引所などの証拠金の現物の価格変動も含まれます）",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "locale", "label": "JPY" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "balance",
     "query": "SELECT cumulative_sum(\"diff_jpy\") as \"Profit\" FROM \"balance\" WHERE \"exchange\"=~/$exchanges$/ and $timeFilter GROUP BY \"exchange\"",
     "select": [
      [
       { "params": [ "jpy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Profit ($inverse_exchange)",
   "type": "graph",
   "description": "インバース契約の取引所用の損益グラフ\n（証拠金の現物の価格変動を含まないグラフをプロットします）",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "BTC (Pos)" }
   ],
   "targets": [
    {
     "alias": "Profit (Include unreal)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(period_prof) FROM (\n    SELECT \"diff_btc\"*\"fixjpy\"/\"fixbtc\" as period_prof FROM \"balance\" WHERE \"exchange\"=~/$inverse_exchange$/ and $timeFilter\n) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Fixed Profit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(period_prof) FROM (\n    SELECT \"diff_fixbtc\"*\"fixjpy\"/\"fixbtc\" as period_prof FROM \"balance\" WHERE \"exchange\"=~/$inverse_exchange$/ and $timeFilter\n) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pos",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean as Position from (SELECT mean(\"pos\") FROM \"balance\" WHERE \"exchange\"=~/$inverse_exchange$/ and $timeFilter GROUP BY time($__interval)) GROUP BY \"exchange\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FX Position ($exchanges)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "BTC" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "balance",
     "query": "SELECT mean as Position from (SELECT mean(\"pos\") FROM \"balance\" WHERE \"exchange\"=~/$exchanges$/ and $timeFilter GROUP BY time($__interval)) GROUP BY \"exchange\"",
     "select": [
      [
       { "params": [ "jpy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Asset ($exchanges)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "locale", "label": "JPY" }
   ],
   "targets": [
    {
     "alias": "Total Asset (include unreal profit)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(mean) FROM (SELECT mean(\"jpy\") FROM \"balance\" WHERE \"exchange\"=~/$exchanges$/ and $timeFilter GROUP BY \"exchange\", time($__interval) fill(null)) GROUP BY time($__interval) fill(previous) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total Asset (fixed profit)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(mean) FROM (SELECT mean(\"fixjpy\") FROM \"balance\" WHERE \"exchange\"=~/$exchanges$/ and $timeFilter GROUP BY \"exchange\", time($__interval) fill(null)) GROUP BY time($__interval) fill(previous) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Asset ($exchanges)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "locale", "label": "JPY" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "balance",
     "query": "SELECT mean as Asset from (SELECT mean(\"jpy\") FROM \"balance\" WHERE \"exchange\"=~/$exchanges$/ and $timeFilter GROUP BY time($__interval)) GROUP BY \"exchange\"",
     "select": [
      [
       { "params": [ "jpy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Market Price (bitFlyerFX , BitMEX)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "XBTUSD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"xbtusd\") as xbtusd FROM \"mex_market\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FX_BTC_JPY",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"fx\") as fxbtcjpy FROM \"bf_market\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "bitFlyer Price Disparity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 18 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "FX_BTC_JPY",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"fx\") as FXBTC FROM \"bf_market\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "BTC_JPY",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"spot\") as BTC FROM \"bf_market\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Price Disparity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"fx\")/mean(\"spot\")-1)*100 as SFD FROM \"bf_market\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OI / OV Bitmex",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Open Interest",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"open_interest\") as xbtusd FROM \"mex_market\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Open Value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"open_value\") as xbtusd FROM \"mex_market\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JPY/USD",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "JPY/USD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"usdjpy\") FROM \"mex_market\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}